// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPRBlJGXNXplWtJA3d-jW7Lp62fI19_m4',
    appId: '1:899763385126:web:2ddedffe9e692eae3d07e7',
    messagingSenderId: '899763385126',
    projectId: 'smart-expense-ai-flutter-app',
    authDomain: 'smart-expense-ai-flutter-app.firebaseapp.com',
    storageBucket: 'smart-expense-ai-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJRq4u2Cn1dJGt4B4tXqB0JNoZA-FGSNE',
    appId: '1:899763385126:android:d8fc16aa7f527e9f3d07e7',
    messagingSenderId: '899763385126',
    projectId: 'smart-expense-ai-flutter-app',
    storageBucket: 'smart-expense-ai-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_E73IpLf07c5UkZCllYbrh4W6dLjPO98',
    appId: '1:899763385126:ios:9f4c8adea70906083d07e7',
    messagingSenderId: '899763385126',
    projectId: 'smart-expense-ai-flutter-app',
    storageBucket: 'smart-expense-ai-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_E73IpLf07c5UkZCllYbrh4W6dLjPO98',
    appId: '1:899763385126:ios:9f4c8adea70906083d07e7',
    messagingSenderId: '899763385126',
    projectId: 'smart-expense-ai-flutter-app',
    storageBucket: 'smart-expense-ai-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPRBlJGXNXplWtJA3d-jW7Lp62fI19_m4',
    appId: '1:899763385126:web:8f86beb0a1eb485e3d07e7',
    messagingSenderId: '899763385126',
    projectId: 'smart-expense-ai-flutter-app',
    authDomain: 'smart-expense-ai-flutter-app.firebaseapp.com',
    storageBucket: 'smart-expense-ai-flutter-app.firebasestorage.app',
  );
}
